layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: ZacNashResearch
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: ZacNashResearch
  # unsplash: your_username
  # vk: your_username
  website: https://research.bangor.ac.uk/portal/en/researchers/john-zachary-nash(05f14617-5901-43f8-b352-cb94f69306ab).html
  # youtube: your_username

topics:
  - name: Marine Robotics
    
    image_url: https://www.hydrologicalusa.com/fileadmin/_processed_/6/4/csm_DSC_1923_7a12ece386.jpg

  - name: Reactive AI
    image_url: https://images.unsplash.com/photo-1534250181471-a453fae2231d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=634&q=80

  - name: Acoustic Telemetry
    web_url: https://github.com/topics/sass
    image_url: https://images.unsplash.com/photo-1578983754681-83bbdfb586a0?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80

theme: jekyll-theme-hacker